# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="sunrise"

# 'ls' relies on this for colors, as well as some other commands
eval `dircolors ~/.dir_colors/solarized_dark`

# Path for fzf plugin to find fzf binary
export FZF_BASE=/usr/share/fzf

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-flow virtualenvwrapper fancy-ctrl-z fzf)

source $ZSH/oh-my-zsh.sh

# Initialize autocompletion with extra functions
fpath=(~/.zsh_functions/completions $fpath)
autoload -U compinit && compinit

# Enable emacs command line edition
bindkey -e

# Customize to your needs...
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/lib/colorgcc/bin
