# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="sunrise"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-flow autojump virtualenvwrapper)

source $ZSH/oh-my-zsh.sh

# Enable emacs command line edition
bindkey -e

# Tells virtualwrapper where is my virtualenv folder
export WORKON_HOME=~/.virtualenvs/

# Customize to your needs...
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/lib/colorgcc/bin

# npm
export PATH="$PATH:$HOME/.npm-packages/bin"

### Added by the Heroku Toolbelt
export PATH="$PATH:/usr/local/heroku/bin"

# Go related
export GOPATH="$HOME/dev/gocode"
export GOROOT="/usr/local/go"
export PATH="$PATH:$GOROOT/bin"

# git-repo
export PATH="$PATH:$HOME/bin"

# Term
export TERM='xterm-256color'

# Aliases

alias djangoshell="python manage.py shell"
alias shellplus="python manage.py shell_plus --use-pythonrc"
alias jb=jobs
alias wttr="curl http://wttr.in/Paris"

function git.send
{
  git push origin `git rev-parse --abbrev-ref HEAD` $1
}

function cdl
{
    cd $1;
    ls;
}

# Ctrl-Z swaps between foreground and background
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z
